name: amazoncorretto-19-debian-slim

on:
  push:
    branches:
    - master
    paths:
      - "amazoncorretto-19-debian-slim/**"
      - .github/workflows/amazoncorretto-19-debian-slim.yml
      - .github/workflows/_template.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"
  pull_request:
    paths:
      - "amazoncorretto-19-debian-slim/**"
      - .github/workflows/amazoncorretto-19-debian-slim.yml
      - .github/workflows/_template.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"

jobs:
  build:
    uses: ./.github/workflows/_template.yml
    with:
      directory: amazoncorretto-19-debian-slim
    secrets: inherit
