name: amazoncorretto-19-windowsservercore

on:
  push:
    paths:
      - "amazoncorretto-19-windowsservercore/**"
      - "tests/**"
      - github-action.ps1
      - "!tests/*.bats"
      - "!tests/*.bash"
      - "!tests/Dockerfile"
      - .github/workflows/_template_windows.yml
  pull_request:
    paths:
      - "amazoncorretto-19-windowsservercore/**"
      - "tests/**"
      - github-action.ps1
      - "!tests/*.bash"
      - "!tests/Dockerfile"
      - .github/workflows/_template_windows.yml

env:
  DOCKER_PUSH: "true"

jobs:
  build:
    uses: ./.github/workflows/_template_windows.yml
    with:
      directory: amazoncorretto-19-windowsservercore
    secrets: inherit
