name: amazoncorretto-17

on:
  push:
    paths:
      - "amazoncorretto-17/**"
      - .github/workflows/amazoncorretto-17.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"
  pull_request:
    paths:
      - "amazoncorretto-17/**"
      - .github/workflows/amazoncorretto-17.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"

jobs:
  build:
    uses: ./.github/workflows/_template.yml
    with:
      directory: amazoncorretto-17
    secrets: inherit
