name: amazoncorretto-11-windowsservercore

on:
  push:
    paths:
      - "amazoncorretto-11-windowsservercore/**"
      - "tests/**"
      - github-action.ps1
      - "!tests/*.bats"
      - "!tests/*.bash"
      - "!tests/Dockerfile"
  pull_request:
    paths:
      - "amazoncorretto-11-windowsservercore/**"
      - "tests/**"
      - github-action.ps1
      - "!tests/*.bash"
      - "!tests/Dockerfile"

env:
  DOCKER_PUSH: "true"

jobs:
  build:
    uses: ./.github/workflows/_template_windows.yml
    with:
      directory: amazoncorretto-11-windowsservercore
    secrets: inherit
