name: azulzulu-25

on:
  push:
    branches:
    - main
    paths:
      - "azulzulu-25/**"
      - .github/workflows/azulzulu-25.yml
      - .github/workflows/_template.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"
  pull_request:
    paths:
      - "azulzulu-25/**"
      - .github/workflows/azulzulu-25.yml
      - .github/workflows/_template.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"

jobs:
  build:
    uses: ./.github/workflows/_template.yml
    with:
      directory: azulzulu-25
    secrets: inherit
