name: eclipse-temurin-8-alpine

on:
  push:
    paths:
      - "eclipse-temurin-8-alpine/**"
      - .github/workflows/eclipse-temurin-8-alpine.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"
  pull_request:
    paths:
      - "eclipse-temurin-8-alpine/**"
      - .github/workflows/eclipse-temurin-8-alpine.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"

jobs:
  build:
    uses: ./.github/workflows/_template.yml
    with:
      directory: eclipse-temurin-8-alpine
    secrets: inherit
