name: graalvm-community-21

on:
  push:
    branches:
    - main
    paths:
      - "graalvm-community-21/**"
      - .github/workflows/graalvm-community-21.yml
      - .github/workflows/_template.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"
  pull_request:
    paths:
      - "graalvm-community-21/**"
      - .github/workflows/graalvm-community-21.yml
      - .github/workflows/_template.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"

jobs:
  build:
    uses: ./.github/workflows/_template.yml
    with:
      directory: graalvm-community-21
    secrets: inherit
