name: ibm-semeru-11-focal

on:
  push:
    paths:
      - "ibm-semeru-11-focal/**"
      - .github/workflows/ibm-semeru-11-focal.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"
  pull_request:
    paths:
      - "ibm-semeru-11-focal/**"
      - .github/workflows/ibm-semeru-11-focal.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"

jobs:
  build:
    uses: ./.github/workflows/_template.yml
    with:
      directory: ibm-semeru-11-focal
    secrets: inherit
