name: microsoft-openjdk-16-ubuntu

on:
  push:
    paths:
      - "microsoft-openjdk-16-ubuntu/**"
      - .github/workflows/microsoft-openjdk-16-ubuntu.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"
  pull_request:
    paths:
      - "microsoft-openjdk-16-ubuntu/**"
      - .github/workflows/microsoft-openjdk-16-ubuntu.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"

jobs:
  build:
    uses: ./.github/workflows/_template.yml
    with:
      directory: microsoft-openjdk-16-ubuntu
    secrets: inherit
