name: oracle-graalvm-17

on:
  push:
    branches:
    - main
    paths:
      - "oracle-graalvm-17/**"
      - .github/workflows/oracle-graalvm-17.yml
      - .github/workflows/_template.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"
  pull_request:
    paths:
      - "oracle-graalvm-17/**"
      - .github/workflows/oracle-graalvm-17.yml
      - .github/workflows/_template.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"

jobs:
  build:
    uses: ./.github/workflows/_template.yml
    with:
      directory: oracle-graalvm-17
    secrets: inherit
