name: sapmachine-22

on:
  push:
    branches:
    - main
    paths:
      - "sapmachine-22/**"
      - .github/workflows/sapmachine-22.yml
      - .github/workflows/_template.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"
  pull_request:
    paths:
      - "sapmachine-22/**"
      - .github/workflows/sapmachine-22.yml
      - .github/workflows/_template.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"

jobs:
  build:
    uses: ./.github/workflows/_template.yml
    with:
      directory: sapmachine-22
    secrets: inherit